name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

env:
  SERVICE_NAME: node-app
  PROJECT_ID: careful-journey-448903-q1
  REGION: asia-south1
  DOCKER_IMAGE: asia-south1-docker.pkg.dev/careful-journey-448903-q1/node-app/node-app

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

        # Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set Up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"
          project_id: ${{ env.PROJECT_ID }}

      - name: Authenticate Docker with Google Artifact Registry
        run: gcloud auth configure-docker asia-south1-docker.pkg.dev

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          image: ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
          region: ${{ env.REGION }}
          allow-unauthenticated: true
